# Generated by Django 6.0.4 on 2026-04-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationjob',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
