# Generated by Django 6.0.4 on 2026-04-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate_model', '0002_evaluationjob_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationjob',
            name='rouge1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationjob',
            name='rouge2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationjob',
            name='rougeL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationjob',
            name='rougeLsum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
