# Generated by Django 6.0.4 on 2026-04-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('findings', models.CharField(max_length=255)),
                ('labels', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
            ],
        ),
    ]
